package com.example.demo.model;

import jakarta.persistence.*;

@Entity
// Marks this class as a JPA entity.
// Spring/JPA will map this class to a database table.
@Table(name = "users")
// Specifies the database table name ("users") that this entity maps to.
public class UserEntity {

  @Id
  // Marks this field as the primary key of the table.
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  // Uses auto-incrementing IDs generated by the database (e.g., PostgreSQL SERIAL or IDENTITY).
  private Long id;

  @Column(unique = true)
  // Ensures the username column has a UNIQUE constraint — no two users can have the same username.
  private String username;

  // Stores the encrypted or plain password depending on your PasswordEncoder configuration.
  private String password;

  // Stores user roles as a String (e.g., "USER", "ADMIN").
  // Spring Security will later read this value to assign authorities.
  private String roles;

  // ----- Getters & Setters -----

  public Long getId() { return id; }
  public void setId(Long id) { this.id = id; }

  public String getUsername() { return username; }
  public void setUsername(String username) { this.username = username; }

  public String getPassword() { return password; }
  public void setPassword(String password) { this.password = password; }

  public String getRoles() { return roles; }
  public void setRoles(String roles) { this.roles = roles; }
}
